apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ngnix-service
spec:
  rules:
    - host: web.cloud-native-santo-domingo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
  ingressClassName: nginx
